### PR TITLE
[Core/StatSystem] Fixed damage values for creatures

### PR DESCRIPTION
**Pull request by SargeroDeV**
* This will reset the behavior of the damage, I will update the stats system later.

### CODE REVIEW

**Comment by leelf00** [comment]
Is another PR depend on this PR?

**Comment by jasongdove** [comment]
I haven't followed the stat system changes, but this tests OK. Melee damage seems much better (e.g. 10k dmg vs 1 dmg from some mobs on Timeless Isle).

:+1:

**Comment by SargeroDeV** [comment]
> Is another PR depend on this PR?

No, this simply restores to how it was before

**Comment by SargeroDeV** [comment]
I converted it to draft for the moment

**Comment by SargeroDeV** [comment]
This PR is ready

**Comment by leelf00** [comment]
I would like to discuss the difference between state systems of TC , AC and SF. I found some information of other cores. https://github.com/azerothcore/azerothcore-wotlk/pull/4749.

**Comment by leelf00** [comment]
@jasongdove @SargeroDeV  Can you give me some information about creatures incorect behavior of the damage.I will compare them with retail Cata Classic version.

**Comment by jasongdove** [comment]
Like I posted in Discord, on current master branch/world db, every creature does 1 melee damage. I believe this is because `creature_classlevelstats` is filled with zeros.

**Comment by leelf00** [comment]
Thanks . I will compare it with TCPP data.

**Pull request merged**
