### PR TITLE
[Core/TerrainSwamps] TerrainSwamps system modernized

### PR DESCRIPTION
**Pull request by SargeroDeV**
You can test its correct functioning by creating a panda, goblin or worgen and making their respective chains. You can check the terrainswamp added by using the gps command.

### CODE REVIEW

**Comment by SargeroDeV** [comment]
This PR is ready

**Comment by leelf00** [comment]
Create a worgen, a after what quest the terrainswamp?

**Comment by SargeroDeV** [comment]
> Create a worgen, a after what quest the terrainswamp?

In the case of worgen it is clear from their conditions:
terrainswamp 655 after 14386,
terrainswamp 656 after 14466

**Comment by leelf00** [comment]
I test PR, it works correctly.

**Pull request merged**
