### PR TITLE
Ignore unnecessary mmaps and map titles errors of Legends of azeroth pandaria 5.4.8

### PR DESCRIPTION
**Pull request by leewheel**
Just not show like
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/0530_32_32.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/0530_31_32.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/0530_31_31.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/1064_31_31.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/1064_32_31.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/1064_32_32.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/1064_31_32.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/0571_31_31.mmtile'
MMAP:loadMap: Could not open mmtile file 'ClientData/mmaps/0571_32_32.mmtile'

### CODE REVIEW

**Comment by leelf00** [comment]
Have you found out the reason for this bug? Extractor not generate these files.

**Comment by leewheel** [comment]
I have been busy with a WoTlk project recently and have not carefully checked the problem. I will study it carefully in a few days.

**Comment by leelf00** [comment]
Thanks.

**Comment by TheYeti** [comment]
No, for some reason the extractor isn't pulling these files from the far edges of the map.  I have tested it and verified using multiple versions of the client data.

**Comment by jasongdove** [comment]
I think I know why this is happening and we can fix a different way. Will link new PR to https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/issues/222

**Comment by leewheel** [comment]
Nice!

**Pull request closed without merging**
