### PR TITLE
[Core] Modernize multiple systems

### PR DESCRIPTION
**Pull request by jasongdove**
This upgrades a few pieces of the core:

1. Full ObjectGuid has been introduced, with corresponding guid generators
2. Global access to all creatures and game objects (e.g. `ObjectAccessor::GetCreatures()`) has been removed
a. These are now tracked and accessed through maps, e.g. `Map::GetCreatureBySpawnIdStore()`
3. Global access to searching creatures and game objects (e.g. `ObjectAccessor::FindCreature(uint64)`) has been removed
a. These are also now only accessed through maps, e.g. `Map::GetCreature(ObjectGuid)`
4. `ByteBuffer` and `WorldPacket` have been upgraded
5. Opcodes and opcode handlers have been upgraded to allow custom packet classes that encapsulate reading and writing data
6. Corpse management has been upgraded
7. Quest relations have been upgraded

---

Bugs introduced by this PR:

- [x] SMSG_QUEST_GIVER_STATUS_MULTIPLE` is improperly formatted
  - Fixed; this was related to byte buffer bit flushing
- [x] Quest log progress resets on logout (complete 6/6 kill objective, log out, log back in and quest log displays 0/6 kills)
  - Not actually introduced by this PR; bug also exists on master branch
- [x] Corpses are broken
  - Fixed; corpse access was also changed from global to map
- [x] April Fools Day event is broken
  - Fixed
- [x] Daily and weekly quest pooling is broken
  - Fixed; upgraded quest pooling system (but not DB tables yet)
- [x] Instance maps are skipped by `MapManager::DoForAllMaps` and `MapManager::DoForAllMapsWithMapId`
  - Fixed

### CODE REVIEW

**Comment by leelf00** [comment]
Test Path

- [ ]  Corpse in instance
- [ ]  World quest pool
- [ ] Game event AprilFoolsDay
- [ ] BattlePay
- [ ] CMSG_GOSSIP_HELLO
- [ ] SMSG_GUILD_CRITERIA_DELETED
- [ ] SMSG_SERVER_FIRST_ACHIEVEMENT
- [ ] SMSG_GUILD_CRITERIA_DATA
- [ ] SMSG_ACCOUNT_CRITERIA_UPDATE
- [ ] SMSG_ACCOUNT_CRITERIA_UPDATE_ALL
- [ ] SMSG_RESPOND_INSPECT_ACHIEVEMENTS
- [ ] SMSG_CHARACTER_UPGRADE_COMPLETE
- [ ] SMSG_BATTLE_PET_DELETED
- [ ] SMSG_BATTLE_PET_SLOT_UPDATE
- [ ] SMSG_BATTLEGROUND_PLAYER_LEFT
- [ ] SMSG_BATTLEGROUND_PLAYER_JOINED
- [ ] SMSG_QUESTGIVER_QUEST_LIST
- [ ] SMSG_QUESTGIVER_STATUS
- [ ] SMSG_QUESTGIVER_REQUEST_ITEMS
- [ ] SMSG_GAMEOBJECT_PAGETEXT
- [ ] SMSG_GAME_OBJECT_ACTIVATE_ANIM_KIT
- [ ] SMSG_SOCKET_GEMS_RESULT
- [ ] SMSG_ARENA_UNIT_DESTROYED
- [ ] SMSG_GAMEOBJECT_DESPAWN_ANIM
- [ ] SMSG_SPELLLOGMISS
- [ ] SMSG_PROC_RESIST
- [ ] SMSG_PLAY_ONE_SHOT_ANIM_KIT
- [ ] SMSG_SET_MOVEMENT_ANIM_KIT
- [ ] SMSG_SET_MELEE_ANIM_KIT
- [ ] SMSG_MOVE_SET_VEHICLE_REC_ID
- [ ] SMSG_MISSILE_CANCEL
- [ ] SMSG_RESUME_CAST_BAR
- [ ] SMSG_LOOT_ROLLS_COMPLETE
- [ ] SMSG_GUILD_RENAMED
- [ ] SMSG_GUILD_EVENT_NEW_LEADER
- [ ] SMSG_GUILD_EVENT_PLAYER_LEFT
- [ ] SMSG_GUILD_EVENT_PRESENCE_CHANGE
- [ ] SMSG_GUILD_EVENT_PLAYER_JOINED
- [ ] SMSG_GUILD_MEMBER_RECIPES
- [ ] SMSG_BATTLEFIELD_MGR_ENTRY_INVITE
- [ ] CMSG_BLACK_MARKET_OPEN
- [ ] SMSG_BLACK_MARKET_OPEN_RESULT
- [ ] CMSG_CALENDAR_GET_CALENDAR
- [ ] CMSG_CALENDAR_UPDATE_EVENT
- [ ] CMSG_CALENDAR_EVENT_REMOVE_INVITE
- [ ] CMSG_CALENDAR_EVENT_MODERATOR_STATUS
- [ ] SMSG_CALENDAR_RAID_LOCKOUT_ADDED
- [ ] CMSG_LFG_SET_BOOT_VOTE
- [ ] SMSG_LFG_ROLE_CHOSEN
- [ ]

**Comment by leelf00** [comment]
@zTerragor Please help to test Raid and Battleground. Others tests work correctly.

**Comment by ctmwow** [comment]
This submission has caused BattlePay's upgraded character level to become invalid

**Comment by leelf00** [comment]
Thanks for information.

**Comment by jasongdove** [comment]
> This submission has caused BattlePay's upgraded character level to become invalid

Please make a new issue with repro steps so we can fix.

**Comment by ctmwow** [comment]
I think the changes in WorldSession:: SendRenameResult should include {}

**Comment by jasongdove** [comment]
> I think the changes in WorldSession:: SendRenameResult should include {}

Yes, good catch. This was a regex change to updated byte buffer. I'll fix and also check other handlers for similar changes.

**Pull request merged**
