### PR TITLE
[Core/SQL/WanderingIsland] Fix quest Not In the Face! (QuestID: 29774)

### PR DESCRIPTION
**Pull request by SargeroDeV**
Already the SmartAI of npc 55556 works correctly, while the script in the core does not.

### CODE REVIEW

**Comment by jasongdove** [comment]
Does this PR depend on another change? I don't have a creature with id 55556 in my world database `creature` table, only `creature_template`.

I'm testing with:
- `.go creature 563604`
- `.quest add 29774`

**Comment by SargeroDeV** [comment]
It is a temporary summon summoned by these lines of SAIs:
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(55477, 0, 1, 2, 19, 0, 100, 0, 29774, 0, 0, 0, 0, 12, 57760, 8, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 'Ji Firepaw - On Accepted Quest - Summon Creature Wugou'),
(55477, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 12, 55556, 8, 0, 0, 0, 0, 8, 0, 0, 0, 0, 665.788, 3136.77, 87.8609, 0.0349066, 'Ji Firepaw - Linked To Id 2 - Summon Creature Shu');

**Comment by jasongdove** [comment]
Ok I got it working, though there are other bugs (abandoning the quest doesn't remove the spirits so there are two of each).

I had to add and complete this quest first https://www.wowhead.com/quest=29772/raucous-rousing - then when I accepted https://www.wowhead.com/quest=29774/not-in-the-face I was able to complete it with the changes from this PR :+1:

**Comment by SargeroDeV** [comment]
The whole pandaren questline has to be fixed from 0 using sniffs as it is full of hackfixes, the reason for this PR is to provisionally complete and follow the questline.

**Pull request merged**
