### PR TITLE
[Tools/VMaps] Update VMaps Part 1

### PR DESCRIPTION
**Pull request by leelf00**
imporve #225

### CODE REVIEW

**Comment by ddk2001** [comment]
M69N)}JWUBU$ L~)00%UN7K
0HLS2CP)1IHV9$0RU29EN P
M9PF1 0Y L`28_EB(JL9NBP

I compiled as per the code you submitted( 2249560), and ran the extract map file, and then prompted these errors. But it is not known if these errors have an effect on the worldsever operation.

**Comment by leelf00** [comment]
Still WIP,not pass test.

**Comment by leelf00** [comment]
Still crash using this PR?

**Comment by ddk2001** [comment]
Yes, the map file extracted with ca7e295 still crashes.

**Comment by leelf00** [comment]
Ok. Maybe cause by mmaps. Can you disable mmaps and try it again?

**Comment by ddk2001** [comment]
I'll try to disable mmap tomorrow.

**Comment by ddk2001** [comment]
I think this vmap extraction is very problematic. This extracted file is only about 1G. I think the normal vmap file is about 2.3G.

**Comment by leelf00** [comment]
vmap folder is 1.7GB

**Comment by ddk2001** [comment]
I tried to disable mmap. When the character is feared, enchanted, confused and other control skills, the server is still down. After I compiled the source code publicised by alexkulya, the extracted vmap is 2.3g. Can you refer to his vmaptools?

**Comment by leelf00** [comment]
I compare both files. m2 files is more in old vmaps folder. Is alexkulya no crash when  character is feared?

**Comment by leelf00** [comment]
Updated. Test if crash.

**Comment by ddk2001** [comment]
Yes, he will not collapse. Indeed, I think sometimes the old one is also good. The source code of PANDARA should mainly fix bugs and supplement missing scripts.

**Comment by ddk2001** [comment]
There are still errors in extraction. I'll try to see if it crashes

**Comment by ddk2001** [comment]
I've tested it, but it still crashes

**Comment by leelf00** [comment]
Quest 14293 still crash?

**Comment by ddk2001** [comment]
It's not just mission 14293, I'm reextracting the map. Maybe I didn't do it just now. I'll test it again when I've got it ready

**Comment by leelf00** [comment]
I test with quest 14293 last day. the quest works correct. I have not tested woth character  feared, enchanted, confused and other control skills

**Comment by ddk2001** [comment]
After my map extraction is completed, I will test whether the task of 14293 and being controlled by skills such as fear and charm will cause downtime. It will take about an hour.

**Comment by ddk2001** [comment]
I tested the task of 14293 once, and it was still down when riding a horse. Then the character is still down after being scared and charmed.

**Comment by ddk2001** [comment]
This task of 14293, after receiving it, will ride a horse. When riding a horse, the server will be down.

**Comment by leelf00** [comment]
Try pull this PR to lastest. I use squash to reduce commits. So you always see one commit here. I tested with quest 14293 with all extract dbc maps vmpas mmaps all and vmaps mmaps enable in config fille, this quest can be done. Can you show some crash logs of this quest?

**Comment by ddk2001** [comment]
You merge the branches and I'll pull them and compile them. I'll see if I can find the complete log. DEBUG compiled cannot run.

**Comment by leelf00** [comment]
Ok. Problem left will improve by next PR.

**Comment by leelf00** [comment]
How to reproduce by npc easily? I will debug the problem with trace log.

**Comment by ddk2001** [comment]
I don't think it's an NPC problem, it's also a lot of quest problems. It's a matter of roles.

**Comment by ddk2001** [comment]
9018  You try this character

**Comment by leelf00** [comment]
npc add temp 9018, test after creature cast fear,not crash

**Comment by ddk2001** [comment]
I'll test it today. Did you advance the map? The vmaps I extracted are still 1G。

**Comment by ddk2001** [comment]
After testing today, there is no downtime.

**Comment by leelf00** [comment]
vmaps and mmaps still not work well.

**Comment by ddk2001** [comment]
Yes, I also found it, but the extracted map information is much better than last time

**Comment by ddk2001** [comment]
There is still boss 69465 at the moment, and when you release Lightning Focus, the server will go down. 56915, as soon as this boss opens, the server crashes, and 71475, 71480 and other bosses will also crash when they release revenge strikes.

**Comment by leelf00** [comment]
Ok. I will try debug tonight. Do you have crash logs of them?

**Comment by ddk2001** [comment]
No. I didn't compile the debug. At present, there are still many downtime bugs.

**Comment by leelf00** [comment]
You can use daily debug windows build on release page. It compiles with RelWithDebugInfo.Daily build can wrtie some crash log.  I debug code under linux, it's hard for me to debug some windows platform only bug.

**Comment by ddk2001** [comment]
Nowadays, many monsters in dungeons fly away.

**Comment by ddk2001** [comment]
I will only do it under Windows. At present, only bugs can be found. Then I'll tell you.

**Comment by ddk2001** [comment]
Do I have to wait until you test 100%? I've been busy lately.

**Comment by leelf00** [comment]
MMaps 80% works except water condition. VMaps still bug, creatures can see you through wall.

**Pull request merged**
