### PR TITLE
[Core/AuctionHouse] Modernize auction house

### PR DESCRIPTION
**Pull request by jasongdove**
This updates the auction house manager code to match TCPP as much as possible. Future PRs might involve porting improvements from TC.

Updating the auction house code required updating the characters database, so I also enabled auto updates there.

- 2024_09_06_xx_characters_update_tables.sql will need to be applied manually
- Afterward, the worldserver can update the auction house tables in the characters db if characters db updates are enabled in the worldserver config

Because of the db changes, all items will be sold to the highest bidder or returned to the owner on server startup, as part of the migration. Future auctions will behave normally.

Note that this does *not* fix the existing bug where bidding on an item will immediately show it as outbit in the bids tab.

### CODE REVIEW

**Comment by leelf00** [comment]
New tables and data missing in sql/base/characters.sql

**Comment by jasongdove** [comment]
> New tables and data missing in sql/base/characters.sql

These have been updated/added.

**Comment by 5840174** [comment]
The auction house item does not display the seller's name
is it because of this change?

**Comment by jasongdove** [comment]
> The auction house item does not display the seller's name
> is it because of this change?

No - the commit before this PR also does not show the seller's name.

**Comment by jasongdove** [comment]
@5840174 names will be fixed with https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/359

**Comment by 5840174** [comment]
Well done

**Pull request merged**
