### PR TITLE
DB/World: Fix missing pandaren shaman action bar

### PR DESCRIPTION
**Pull request by zTerragor**
DB/World: Fix missing pandaren shaman action bar

### CODE REVIEW

**Comment by jasongdove** [comment]
I can take care of all of the Pandaren action bars.

**Comment by leelf00** [comment]
Table and full feature is missing.

**Comment by jasongdove** [comment]
Ah, I misunderstood. I thought I was assigned to finish developing this. Yeah, the first table doesn't exist and the bar is incomplete.

**Comment by jasongdove** [comment]
I posted what I started (based on this PR) in case it's useful. See https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/268

**Comment by jasongdove** [comment]
@zTerragor Pandaren action bars for all classes were fixed with https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/268 - please confirm.

**Comment by leelf00** [comment]
Closed by https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/268

**Comment by leelf00** [comment]
Fixed by https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/268

**Pull request closed without merging**
