### PR TITLE
[Core/Maps]/ Activate creatures and objects during opening cinematics…

### PR DESCRIPTION
**Pull request by SargeroDeV**
… and other flyby cameras.

### CODE REVIEW

**Comment by leelf00** [comment]
How to test this PR?

**Comment by SargeroDeV** [comment]
> How to test this PR?

Creating a new player

**Comment by jasongdove** [comment]
There is a case-sensitivity mismatch between the map extractor and the new loader. For example, my cameras folder has `FlyByTauren.m2` but I see an error on startup about loading `flybytauren.m2`.

I think another change is needed to make this work for data extracted using the tools from this repo.

**Comment by jasongdove** [comment]
Thanks for the PR! I didn't know why cinematics were empty before.

I referenced many of the changes here to create a new PR that I think will be better for the project in the long term since other things rely on the same far sight code that cinematics use.

**Pull request closed without merging**
